import re
import streamlit as st
from streamlit_chat import message
import random

asked_questions = set()  # Check if the question has already been asked

    # Fallback responses to handle undefined input
fallback_responses = [
    "Alright, let's explore something else.",
    "Let's change the subject a bit.",
    "How about we switch gears?",
    "Let’s move on to another topic.",
    "Let’s change direction a little.",
    "How about we talk about something different?",
    "Alright, let's dive into another topic.",
    "Let’s shift the conversation.",
    "Let’s explore a new subject.",
    "How about we move to a different area?",
    "Let’s turn to a new topic.",
    "Alright, let’s talk about something else.",
    "Let’s move on and talk about something fresh.",
    "How about we change focus?",
    "Let’s take a new direction.",
    "Let’s talk about something different now.",
    "Alright, let’s dive into something else.",
    "How about we shift topics?",
    "Let’s switch it up a bit.",
    "Let’s move on and discuss something new.",
    "Let’s change it up and talk about something else.",
    "Alright, let's discuss something else.",
    "Let’s talk about something fresh.",
    "How about we explore a different topic?",
    "Let’s take this conversation in a new direction.",
    "Alright, let’s move on to a different discussion.",
    "Let’s shift focus to something else.",
    "How about we talk about something else for a change?",
    "Let’s take the conversation elsewhere.",
    "Alright, let’s head in a new direction.",
    "Let’s switch things around a bit.",
    "Let’s move on and try something new.",
    "Alright, let’s dive into another area of discussion.",
    "How about we explore a different perspective?",
    "Let’s change topics and talk about something new.",
    "Alright, let’s move forward with a new subject.",
    "Let’s jump into something else.",
    "How about we explore a different angle?",
    "Let’s change the conversation a bit.",
    "Alright, let’s talk about something else for a while.",
    "Let’s shift to a new subject.",
    "How about we turn to something else?",
    "Let’s change the conversation a bit.",
    "Alright, let’s dive into a new area.",
    "Let’s move to a fresh topic.",
    "Let’s explore something new and different.",
    "How about we talk about something fresh?",
    "Let’s switch to something else.",
    "Alright, let’s explore a different direction.",
    "Let’s change the focus of the conversation.",
    "How about we jump to a new subject?",
    "Let’s talk about something different.",
    "Alright, let’s move on and explore something new.",
    "Let’s change the topic for a bit.",
    "How about we turn to something else now?",
    "Let’s talk about something else for a moment.",
    "Alright, let’s shift to a new topic.",
    "Let’s try a different conversation.",
    "Let’s explore another area.",
    "Alright, let’s switch up the conversation.",
    "Let’s head in a new direction.",
    "Let’s change the focus a bit.",
    "How about we talk about something fresh?",
    "Let’s dive into something different now.",
    "Let’s move to a different topic now.",
    "Alright, let’s explore something fresh.",
    "Let’s shift the focus to something else.",
    "How about we jump into a new subject?",
    "Let’s take a different approach and talk about something else.",
    "Alright, let’s change gears.",
    "Let’s move ahead with a new topic.",
    "How about we shift to another area?",
    "Let’s talk about something fresh now.",
    "Alright, let’s explore a different subject.",
    "Let’s dive into something else entirely.",
    "How about we try a new direction?",
    "Let’s shift focus to something different.",
    "Alright, let’s discuss something else for now.",
    "Let’s talk about something else briefly.",
    "How about we explore a new topic?",
    "Let’s talk about something fresh for a bit.",
    "Alright, let’s dive into a different topic.",
    "Let’s change things up and talk about something new.",
    "Let’s shift to a fresh subject.",
    "How about we move on and try something else?",
    "Let’s talk about something else now.",
    "Alright, let’s move on and switch topics.",
    "Let’s change the focus and explore something else."
]

    
used_fallbacks = set()  # Track fallback responses already used

def get_fallback_response(questions, used_fallbacks):
    available_questions = [q for q in questions if q not in asked_questions]
    if not available_questions:
        return "Ok good bye!"
    
    question = random.choice(available_questions)
    used_fallbacks.add(question)
    return question

# Function to generate a response
def generate_response(user_input, asked_questions):
    patterns = [
        (r"(.*)name(.*)", "How old are you?"),
        (r"(?:.*\b(?:old\b|\d+)\b.*)", "Tell me about your experience with python"),
        (r"(.*)passion(.*)", "What are you most passionate about in your work?"),
        (r"(.*)challenge(.*)", "What is the biggest challenge you have overcome in your career?"),
        (r"(.*)motivation(.*)", "What motivates you to excel in your field?"),
        (r"(.*)failure(.*)", "Can you share a failure you’ve experienced and how you handled it?"),
        (r"(.*)success(.*)", "What does success mean to you in your professional life?"),
        (r"(.*)growth(.*)", "How do you ensure continuous personal and professional growth?"),
        (r"(.*)strength(.*)", "What do you consider to be your greatest strength?"),
        (r"(.*)weakness(.*)", "What is an area where you feel you could improve?"),
        (r"(.*)inspiration(.*)", "Who or what has inspired you most in your career?"),
        (r"(.*)goal(.*)", "What is a personal or professional goal you’re currently working toward?"),
        (r"(.*)decision(.*)", "Can you share an important decision you made and its impact?"),
        (r"(.*)learning(.*)", "What is the most valuable thing you’ve learned recently?"),
        (r"(.*)mentor(.*)", "Have you had a mentor who shaped your career? What did you learn?"),
        (r"(.*)team(.*)", "How do you approach working within a team?"),
        (r"(.*)independence(.*)", "Can you describe a time when you worked independently to achieve a goal?"),
        (r"(.*)leadership(.*)", "What does effective leadership mean to you?"),
        (r"(.*)value(.*)", "What values are most important to you in a workplace?"),
        (r"(.*)adaptability(.*)", "Can you share an instance where you had to adapt quickly to change?"),
        (r"(.*)resilience(.*)", "How do you build resilience when faced with setbacks?"),
        (r"(.*)time(.*)", "How do you prioritize your time when juggling multiple tasks?"),
        (r"(.*)stress(.*)", "How do you handle stressful situations?"),
        (r"(.*)feedback(.*)", "How do you approach giving and receiving feedback?"),
        (r"(.*)collaboration(.*)", "Can you share a time when collaboration led to better results?"),
        (r"(.*)conflict(.*)", "How do you manage conflicts in a professional setting?"),
        (r"(.*)curiosity(.*)", "What’s something new you’ve been curious to learn about?"),
        (r"(.*)failure(.*)", "How do you deal with failure and bounce back?"),
        (r"(.*)decision-making(.*)", "What is your decision-making process?"),
        (r"(.*)communication(.*)", "How do you ensure effective communication in a project?"),
        (r"(.*)initiative(.*)", "Can you provide an example of a time you took the initiative?"),
        (r"(.*)career path(.*)", "What inspired you to choose your career path?"),
        (r"(.*)success(.*)", "Can you describe a success you are particularly proud of?"),
        (r"(.*)motivation(.*)", "What drives you to perform your best?"),
        (r"(.*)learning style(.*)", "How do you approach learning new skills?"),
        (r"(.*)problem-solving(.*)", "Can you share a problem you solved creatively?"),
        (r"(.*)resourcefulness(.*)", "How do you demonstrate resourcefulness in challenging situations?"),
        (r"(.*)ambition(.*)", "What are your ambitions for the next five years?"),
        (r"(.*)vision(.*)", "What is your vision for your future career?"),
        (r"(.*)role model(.*)", "Who is a role model in your life and why?"),
        (r"(.*)habit(.*)", "What habits help you stay productive?"),
        (r"(.*)balance(.*)", "How do you maintain a work-life balance?"),
        (r"(.*)hobby(.*)", "What are your hobbies, and how do they influence your work?"),
        (r"(.*)education(.*)", "How has your education shaped your approach to work?"),
        (r"(.*)decision-making(.*)", "What is the toughest decision you’ve had to make at work?"),
        (r"(.*)priorities(.*)", "How do you determine your priorities?"),
        (r"(.*)dream(.*)", "What is your dream project?"),
        (r"(.*)risk(.*)", "Can you share a time you took a professional risk?"),
        (r"(.*)innovation(.*)", "What’s an innovative idea you’ve brought to a team?"),
        (r"(.*)network(.*)", "How do you build and maintain professional relationships?"),
        (r"(.*)integrity(.*)", "What does integrity mean to you?"),
        (r"(.*)creativity(.*)", "How do you express creativity in your work?"),
        (r"(.*)empathy(.*)", "Can you share a time when empathy helped you in your role?"),
        (r"(.*)efficiency(.*)", "How do you ensure efficiency in your work?"),
        (r"(.*)opportunity(.*)", "What opportunities are you most excited about right now?"),
        (r"(.*)focus(.*)", "How do you maintain focus during complex tasks?"),
        (r"(.*)initiative(.*)", "Can you describe a time you went beyond expectations?"),
        (r"(.*)career(.*)", "What’s been the most defining moment in your career?"),
        (r"(.*)adaptability(.*)", "How do you adjust to new environments?"),
        (r"(.*)vision(.*)", "How do you translate vision into actionable plans?"),
        (r"(.*)conflict(.*)", "How do you navigate disagreements in a professional setting?"),
        (r"(.*)recognition(.*)", "How do you prefer to be recognized for your work?"),
        (r"(.*)networking(.*)", "What role has networking played in your career?"),
        (r"(.*)ambition(.*)", "What’s the most ambitious goal you’ve set for yourself?"),
        (r"(.*)strategy(.*)", "How do you approach creating a strategy?"),
        (r"(.*)failure(.*)", "What’s a failure that taught you an important lesson?"),
        (r"(.*)support(.*)", "How do you support colleagues in challenging situations?"),
        (r"(.*)drive(.*)", "What drives your passion for your field?"),
        (r"(.*)adaptation(.*)", "Can you share an example of a time you adapted to a new role?"),
        (r"(.*)career development(.*)", "How do you approach career development?"),
        (r"(.*)confidence(.*)", "What role does confidence play in your success?"),
        (r"(.*)mistake(.*)", "How do you handle mistakes at work?"),
        (r"(.*)ambition(.*)", "What personal ambition keeps you motivated?"),
        (r"(.*)creativity(.*)", "What’s the most creative solution you’ve proposed?"),
        (r"(.*)feedback(.*)", "What’s the most valuable feedback you’ve received?"),
        (r"(.*)project(.*)", "Can you describe a challenging project and your role in it?"),
        (r"(.*)learning experience(.*)", "What’s been your most significant learning experience?"),
        (r"(.*)mentor(.*)", "What’s a piece of advice from a mentor you’ve found invaluable?"),
        (r"(.*)leadership(.*)", "How do you define leadership in your work?"),
        (r"(.*)confidence(.*)", "What helps you maintain confidence under pressure?"),
        (r"(.*)problem-solving(.*)", "What’s a problem you solved that you’re proud of?"),
        (r"(.*)opportunity(.*)", "How do you recognize and seize opportunities?"),
        (r"(.*)vision(.*)", "What is your long-term vision for your career?"),
        (r"(.*)adaptability(.*)", "Can you share a time you adapted your approach to achieve success?"),
        (r"(.*)teamwork(.*)", "What’s the most valuable lesson you’ve learned about teamwork?"),
        (r"(.*)motivation(.*)", "What keeps you motivated during difficult projects?"),
        (r"(.*)integrity(.*)", "How do you demonstrate integrity in your work?"),
        (r"(.*)initiative(.*)", "What’s an example of you taking initiative at work?"),
        (r"(.*)decision-making(.*)", "What’s a decision you made that had a lasting impact?"),
        (r"(.*)stress(.*)", "How do you stay productive under stress?"),
        (r"(.*)learning style(.*)", "What’s your preferred learning style, and how do you use it?"),
        (r"(.*)balance(.*)", "How do you balance competing priorities?"),
        (r"(.*)feedback(.*)", "How has feedback shaped your career?"),
        (r"(.*)success(.*)", "What do you consider your greatest professional success?"),
        (r"(.*)failure(.*)", "What failure helped you grow the most?"),
        (r"(.*)passion(.*)", "What are you most passionate about in your work?"),
        (r"(.*)challenge(.*)", "What is the biggest challenge you have overcome in your career?"),
        (r"(.*)motivation(.*)", "What motivates you to excel in your field?"),
        (r"(.*)failure(.*)", "Can you share a failure you’ve experienced and how you handled it?"),
        (r"(.*)success(.*)", "What does success mean to you in your professional life?"),
        (r"(.*)growth(.*)", "How do you ensure continuous personal and professional growth?"),
        (r"(.*)strength(.*)", "What do you consider to be your greatest strength?"),
        (r"(.*)weakness(.*)", "What is an area where you feel you could improve?"),
        (r"(.*)inspiration(.*)", "Who or what has inspired you most in your career?"),
        (r"(.*)goal(.*)", "What is a personal or professional goal you’re currently working toward?"),
        (r"(.*)decision(.*)", "Can you share an important decision you made and its impact?"),
        (r"(.*)learning(.*)", "What is the most valuable thing you’ve learned recently?"),
        (r"(.*)mentor(.*)", "Have you had a mentor who shaped your career? What did you learn?"),
        (r"(.*)team(.*)", "How do you approach working within a team?"),
        (r"(.*)independence(.*)", "Can you describe a time when you worked independently to achieve a goal?"),
        (r"(.*)leadership(.*)", "What does effective leadership mean to you?"),
        (r"(.*)value(.*)", "What values are most important to you in a workplace?"),
        (r"(.*)adaptability(.*)", "Can you share an instance where you had to adapt quickly to change?"),
        (r"(.*)resilience(.*)", "How do you build resilience when faced with setbacks?"),
        (r"(.*)time(.*)", "How do you prioritize your time when juggling multiple tasks?"),
        (r"(.*)stress(.*)", "How do you handle stressful situations?"),
        (r"(.*)feedback(.*)", "How do you approach giving and receiving feedback?"),
        (r"(.*)collaboration(.*)", "Can you share a time when collaboration led to better results?"),
        (r"(.*)conflict(.*)", "How do you manage conflicts in a professional setting?"),
        (r"(.*)curiosity(.*)", "What’s something new you’ve been curious to learn about?"),
        (r"(.*)failure(.*)", "How do you deal with failure and bounce back?"),
        (r"(.*)decision-making(.*)", "What is your decision-making process?"),
        (r"(.*)communication(.*)", "How do you ensure effective communication in a project?"),
        (r"(.*)initiative(.*)", "Can you provide an example of a time you took the initiative?"),
        (r"(.*)career path(.*)", "What inspired you to choose your career path?"),
        (r"(.*)success(.*)", "Can you describe a success you are particularly proud of?"),
        (r"(.*)motivation(.*)", "What drives you to perform your best?"),
        (r"(.*)learning style(.*)", "How do you approach learning new skills?"),
        (r"(.*)problem-solving(.*)", "Can you share a problem you solved creatively?"),
        (r"(.*)resourcefulness(.*)", "How do you demonstrate resourcefulness in challenging situations?"),
        (r"(.*)ambition(.*)", "What are your ambitions for the next five years?"),
        (r"(.*)vision(.*)", "What is your vision for your future career?"),
        (r"(.*)role model(.*)", "Who is a role model in your life and why?"),
        (r"(.*)habit(.*)", "What habits help you stay productive?"),
        (r"(.*)balance(.*)", "How do you maintain a work-life balance?"),
        (r"(.*)hobby(.*)", "What are your hobbies, and how do they influence your work?"),
        (r"(.*)education(.*)", "How has your education shaped your approach to work?"),
        (r"(.*)decision-making(.*)", "What is the toughest decision you’ve had to make at work?"),
        (r"(.*)priorities(.*)", "How do you determine your priorities?"),
        (r"(.*)dream(.*)", "What is your dream project?"),
        (r"(.*)risk(.*)", "Can you share a time you took a professional risk?"),
        (r"(.*)innovation(.*)", "What’s an innovative idea you’ve brought to a team?"),
        (r"(.*)network(.*)", "How do you build and maintain professional relationships?"),
        (r"(.*)integrity(.*)", "What does integrity mean to you?"),
        (r"(.*)creativity(.*)", "How do you express creativity in your work?"),
        (r"(.*)empathy(.*)", "Can you share a time when empathy helped you in your role?"),
        (r"(.*)efficiency(.*)", "How do you ensure efficiency in your work?"),
        (r"(.*)opportunity(.*)", "What opportunities are you most excited about right now?"),
        (r"(.*)focus(.*)", "How do you maintain focus during complex tasks?"),
        (r"(.*)initiative(.*)", "Can you describe a time you went beyond expectations?"),
        (r"(.*)career(.*)", "What’s been the most defining moment in your career?"),
        (r"(.*)adaptability(.*)", "How do you adjust to new environments?"),
        (r"(.*)vision(.*)", "How do you translate vision into actionable plans?"),
        (r"(.*)conflict(.*)", "How do you navigate disagreements in a professional setting?"),
        (r"(.*)recognition(.*)", "How do you prefer to be recognized for your work?"),
        (r"(.*)networking(.*)", "What role has networking played in your career?"),
        (r"(.*)ambition(.*)", "What’s the most ambitious goal you’ve set for yourself?"),
        (r"(.*)strategy(.*)", "How do you approach creating a strategy?"),
        (r"(.*)failure(.*)", "What’s a failure that taught you an important lesson?"),
        (r"(.*)support(.*)", "How do you support colleagues in challenging situations?"),
        (r"(.*)drive(.*)", "What drives your passion for your field?"),
        (r"(.*)adaptation(.*)", "Can you share an example of a time you adapted to a new role?"),
        (r"(.*)career development(.*)", "How do you approach career development?"),
        (r"(.*)confidence(.*)", "What role does confidence play in your success?"),
        (r"(.*)mistake(.*)", "How do you handle mistakes at work?"),
        (r"(.*)ambition(.*)", "What personal ambition keeps you motivated?"),
        (r"(.*)creativity(.*)", "What’s the most creative solution you’ve proposed?"),
        (r"(.*)feedback(.*)", "What’s the most valuable feedback you’ve received?"),
        (r"(.*)project(.*)", "Can you describe a challenging project and your role in it?"),
        (r"(.*)learning experience(.*)", "What’s been your most significant learning experience?"),
        (r"(.*)mentor(.*)", "What’s a piece of advice from a mentor you’ve found invaluable?"),
        (r"(.*)leadership(.*)", "How do you define leadership in your work?"),
        (r"(.*)confidence(.*)", "What helps you maintain confidence under pressure?"),
        (r"(.*)problem-solving(.*)", "What’s a problem you solved that you’re proud of?"),
        (r"(.*)opportunity(.*)", "How do you recognize and seize opportunities?"),
        (r"(.*)vision(.*)", "What is your long-term vision for your career?"),
        (r"(.*)adaptability(.*)", "Can you share a time you adapted your approach to achieve success?"),
        (r"(.*)teamwork(.*)", "What’s the most valuable lesson you’ve learned about teamwork?"),
        (r"(.*)motivation(.*)", "What keeps you motivated during difficult projects?"),
        (r"(.*)integrity(.*)", "How do you demonstrate integrity in your work?"),
        (r"(.*)initiative(.*)", "What’s an example of you taking initiative at work?"),
        (r"(.*)decision-making(.*)", "What’s a decision you made that had a lasting impact?"),
        (r"(.*)stress(.*)", "How do you stay productive under stress?"),
        (r"(.*)learning style(.*)", "What’s your preferred learning style, and how do you use it?"),
        (r"(.*)balance(.*)", "How do you balance competing priorities?"),
        (r"(.*)feedback(.*)", "How has feedback shaped your career?"),
        (r"(.*)success(.*)", "What do you consider your greatest professional success?"),
        (r"(.*)failure(.*)", "What failure helped you grow the most?"),
        (r"(.*)motivation(.*)", "What motivates you to excel in your field?"),
        (r"(.*)failure(.*)", "Can you share a failure you've experienced and how you handled it?"),
        (r"(.*)challenge(.*)", "Could you tell me about a challenging situation you've faced?"),
        (r"(.*)teamwork(.*)", "Tell me about a time when you had to work closely with someone whose personality was very different from yours."),
        (r"(.*)deadline(.*)", "Describe a situation where you had to meet a tight deadline. How did you manage it?"),
        (r"(.*)conflict(.*)", "Share an experience where you had to resolve a conflict between team members."),
        (r"(.*)initiative(.*)", "Tell me about a time you saw a problem and took the initiative to correct it."),
        (r"(.*)pressure(.*)", "Describe a time when you worked under intense pressure. How did you handle it?"),
        (r"(.*)mistake(.*)", "Tell me about a time you made a mistake. How did you handle it?"),
        (r"(.*)feedback(.*)", "Share an instance when you received negative feedback. How did you respond?"),
        (r"(.*)goal(.*)", "Describe a goal you set and how you achieved it."),
        (r"(.*)disagreement(.*)", "Tell me about a time you disagreed with a supervisor's decision. How did you handle it?"),
        (r"(.*)change(.*)", "Share an experience where you had to adapt to a significant change."),
        (r"(.*)priority(.*)", "Describe a situation where you had to juggle multiple priorities. How did you organize your time?"),
        (r"(.*)difficult decision(.*)", "Tell me about a difficult decision you had to make at work."),
        (r"(.*)leadership(.*)", "Share an experience where you had to lead a team through a challenging situation."),
        (r"(.*)innovation(.*)", "Describe a time when you came up with an innovative solution to a problem."),
        (r"(.*)failure(.*)", "Tell me about a project that failed. What did you learn from it?"),
        (r"(.*)communication(.*)", "Share an example of how you handled a communication breakdown."),
        (r"(.*)motivation(.*)", "Describe a situation where you had to motivate a demoralized team."),
        (r"(.*)budget(.*)", "Tell me about a time you had to work with a tight budget."),
        (r"(.*)ethical(.*)", "Share an experience where you faced an ethical dilemma at work."),
        (r"(.*)diversity(.*)", "Describe a situation where you worked with a diverse team."),
        (r"(.*)overworked(.*)", "Tell me about a time you felt overworked. How did you handle it?"),
        (r"(.*)mentor(.*)", "Share an experience where you had to mentor someone."),
        (r"(.*)criticism(.*)", "Describe how you handled constructive criticism."),
        (r"(.*)risk(.*)", "Tell me about a calculated risk you took at work."),
        (r"(.*)quality(.*)", "Share a situation where you had to sacrifice quality for speed, or vice versa."),        (r"(.*)(machine learning|ML)(.*)", "Can you describe what machine learning is?"),
        (r"(.*)(programming|coding)(.*)", "What programming languages are you most comfortable with?"),
        (r"(.*)machine learning(.*)", "Can you explain your experience with machine learning models?"),
        (r"(.*)deep learning(.*)", "What’s the most complex deep learning project you’ve worked on?"),
        (r"(.*)framework(.*)", "Which AI frameworks are you most comfortable working with?"),
        (r"(.*)data preprocessing(.*)", "How do you approach preprocessing data for machine learning models?"),
        (r"(.*)dataset(.*)", "Can you describe a challenging dataset you worked with and how you handled it?"),
        (r"(.*)NLP(.*)", "What experience do you have with natural language processing?"),
        (r"(.*)computer vision(.*)", "Can you discuss your experience with computer vision applications?"),
        (r"(.*)TensorFlow(.*)", "What’s your experience with TensorFlow?"),
        (r"(.*)PyTorch(.*)", "How have you used PyTorch in your projects?"),
        (r"(.*)deployment(.*)", "Can you explain how you deploy machine learning models in production?"),
        (r"(.*)cloud(.*)", "What cloud platforms have you used for AI projects?"),
        (r"(.*)AWS(.*)", "What services in AWS have you used for machine learning or AI?"),
        (r"(.*)Google Cloud(.*)", "How have you utilized Google Cloud for AI development?"),
        (r"(.*)Azure(.*)", "What’s your experience with Azure’s AI offerings?"),
        (r"(.*)scikit-learn(.*)", "How do you use scikit-learn in your work?"),
        (r"(.*)pandas(.*)", "How do you use pandas for data analysis in your projects?"),
        (r"(.*)model optimization(.*)", "Can you describe your approach to optimizing machine learning models?"),
        (r"(.*)hyperparameter(.*)", "How do you tune hyperparameters for your models?"),
        (r"(.*)GPU(.*)", "What experience do you have with GPU acceleration for training models?"),
        (r"(.*)edge AI(.*)", "Have you worked on deploying AI models on edge devices?"),
        (r"(.*)big data(.*)", "How do you handle large datasets in your projects?"),
        (r"(.*)SQL(.*)", "What’s your experience with databases and SQL for AI development?"),
        (r"(.*)API(.*)", "How do you integrate AI models with APIs?"),
        (r"(.*)REST(.*)", "Can you discuss how you’ve worked with REST APIs in AI applications?"),
        (r"(.*)CI/CD(.*)", "How do you incorporate CI/CD practices in AI model development?"),
        (r"(.*)git(.*)", "How do you use version control systems like Git in your projects?"),
        (r"(.*)testing(.*)", "How do you test machine learning models before deployment?"),
        (r"(.*)debugging(.*)", "What’s your approach to debugging a machine learning model?"),
        (r"(.*)ethics(.*)", "How do you approach ethical considerations in AI development?"),
        (r"(.*)bias(.*)", "How do you detect and mitigate bias in AI models?"),
        (r"(.*)explainability(.*)", "What tools or methods do you use for AI model explainability?"),
        (r"(.*)evaluation(.*)", "How do you evaluate the performance of an AI model?"),
        (r"(.*)metrics(.*)", "What metrics do you typically use to assess machine learning models?"),
        (r"(.*)classification(.*)", "How do you handle imbalanced classes in a classification problem?"),
        (r"(.*)regression(.*)", "What’s your approach to solving regression problems?"),
        (r"(.*)clustering(.*)", "Can you describe your experience with clustering algorithms?"),
        (r"(.*)anomaly detection(.*)", "What techniques do you use for anomaly detection?"),
        (r"(.*)transfer learning(.*)", "How have you applied transfer learning in your projects?"),
        (r"(.*)reinforcement learning(.*)", "What’s your experience with reinforcement learning?"),
        (r"(.*)GAN(.*)", "Have you worked with generative adversarial networks (GANs)?"),
        (r"(.*)LSTM(.*)", "How have you used LSTMs in sequence modeling tasks?"),
        (r"(.*)transformer(.*)", "Can you explain your experience with transformer models?"),
        (r"(.*)BERT(.*)", "Have you implemented or fine-tuned BERT in your projects?"),
        (r"(.*)chatbot(.*)", "What experience do you have in developing chatbots?"),
        (r"(.*)recommendation system(.*)", "How have you developed or optimized recommendation systems?"),
        (r"(.*)speech recognition(.*)", "What experience do you have with speech recognition technologies?"),
        (r"(.*)image processing(.*)", "Can you describe your work with image processing techniques?"),
        (r"(.*)data pipeline(.*)", "How do you design and maintain data pipelines for AI projects?"),
        (r"(.*)scalability(.*)", "What’s your approach to ensuring scalability in AI applications?"),
        (r"(.*)cross-validation(.*)", "How do you use cross-validation in model development?"),
        (r"(.*)regularization(.*)", "What techniques do you use for regularization?"),
        (r"(.*)dimensionality reduction(.*)", "Can you discuss your experience with dimensionality reduction techniques?"),
        (r"(.*)PCA(.*)", "Have you used Principal Component Analysis (PCA)? For what purpose?"),
        (r"(.*)ensemble(.*)", "What’s your approach to building ensemble models?"),
        (r"(.*)time series(.*)", "How do you handle time series data in your projects?"),
        (r"(.*)EDA(.*)", "What’s your process for exploratory data analysis (EDA)?"),
        (r"(.*)automation(.*)", "How have you automated repetitive tasks in AI workflows?"),
        (r"(.*)open source(.*)", "What open-source projects or libraries have you contributed to?"),
        (r"(.*)documentation(.*)", "How do you document your AI projects for reproducibility?"),
        (r"(.*)project management(.*)", "How do you manage timelines and deliverables for AI projects?"),
        (r"(.*)team(.*)", "How do you collaborate effectively with cross-functional teams?"),
        (r"(.*)leadership(.*)", "What leadership roles have you taken on in AI projects?"),
        (r"(.*)mentorship(.*)", "Have you mentored junior AI developers? What was your approach?"),
        (r"(.*)continuous learning(.*)", "How do you stay updated with the latest advancements in AI?"),
        (r"(.*)papers(.*)", "What recent AI research papers have you found particularly interesting?"),
        (r"(.*)innovation(.*)", "Can you describe an innovative AI solution you developed?"),
        (r"(.*)hackathon(.*)", "Have you participated in AI hackathons? What was your experience?"),
        (r"(.*)tools(.*)", "What tools do you find most useful in your AI development work?"),
        (r"(.*)DevOps(.*)", "How have you worked with DevOps teams for AI deployments?"),
        (r"(.*)version control(.*)", "How do you use version control for managing AI projects?"),
        (r"(.*)security(.*)", "How do you ensure security and privacy in AI systems?"),
        (r"(.*)integration(.*)", "Can you discuss how you’ve integrated AI solutions into existing systems?"),
        (r"(.*)risk(.*)", "What risks do you consider when deploying AI solutions?"),
        (r"(.*)optimization(.*)", "How do you optimize AI systems for cost and performance?"),
        (r"(.*)visualization(.*)", "What tools do you use for visualizing AI model performance?"),
        (r"(.*)versioning(.*)", "How do you handle versioning for machine learning models?"),
        (r"(.*)AB testing(.*)", "What’s your experience with A/B testing in AI projects?"),
        (r"(.*)scaling(.*)", "How have you scaled AI solutions for large user bases?"),
        (r"(.*)object detection(.*)", "What techniques have you used for object detection tasks?"),
        (r"(.*)image segmentation(.*)", "How have you handled image segmentation projects?"),
        (r"(.*)data augmentation(.*)", "What methods do you use for data augmentation?"),
        (r"(.*)transferable skills(.*)", "What skills from your previous roles have been most transferable to AI development?"),
        (r"(.*)prototyping(.*)", "How do you approach prototyping AI solutions?"),
        (r"(.*)scalability(.*)", "Can you discuss an example where you ensured scalability in an AI solution?"),
        (r"(.*)career(.*)", "What are your long-term career goals in AI development?"),
        (r"(.*)NumPy(.*)", "How do you use NumPy in your AI projects?"),
        (r"(.*)Pandas(.*)", "What advanced data manipulation techniques do you use with Pandas?"),
        (r"(.*)Matplotlib(.*)", "How do you visualize data using Matplotlib?"),
        (r"(.*)Seaborn(.*)", "Can you discuss how you create detailed visualizations using Seaborn?"),
        (r"(.*)Scikit-learn(.*)", "How do you leverage Scikit-learn for machine learning tasks?"),
        (r"(.*)XGBoost(.*)", "What’s your experience with XGBoost for model development?"),
        (r"(.*)LightGBM(.*)", "When do you prefer LightGBM over other gradient boosting frameworks?"),
        (r"(.*)CatBoost(.*)", "Can you describe how you’ve used CatBoost in your projects?"),
        (r"(.*)statsmodels(.*)", "How do you use statsmodels for statistical analysis?"),
        (r"(.*)Plotly(.*)", "What’s your experience with interactive data visualization in Plotly?"),
        (r"(.*)Altair(.*)", "How do you create declarative visualizations using Altair?"),
        (r"(.*)Dask(.*)", "What’s your approach to handling large datasets with Dask?"),
        (r"(.*)Hugging Face(.*)", "How have you used Hugging Face transformers in NLP tasks?"),
        (r"(.*)Keras(.*)", "What advantages do you find in using Keras for deep learning projects?"),
        (r"(.*)OpenCV(.*)", "How have you used OpenCV for image processing tasks?"),
        (r"(.*)PyCaret(.*)", "What’s your experience with PyCaret for automating machine learning workflows?"),
        (r"(.*)Bokeh(.*)", "How do you create interactive visualizations using Bokeh?"),
        (r"(.*)Dash(.*)", "Can you describe a dashboard you built using Dash?"),
        (r"(.*)NetworkX(.*)", "What’s your experience with graph-based data analysis using NetworkX?"),
        (r"(.*)PySpark(.*)", "How have you used PySpark for distributed data processing?"),
        (r"(.*)pytorch-lightning(.*)", "What’s your experience with PyTorch Lightning for structured deep learning?"),
        (r"(.*)fastai(.*)", "How have you used fastai to simplify model training?"),
        (r"(.*)SpaCy(.*)", "What’s your approach to NLP using SpaCy?"),
        (r"(.*)NLTK(.*)", "How do you use NLTK for natural language processing?"),
        (r"(.*)Gensim(.*)", "What’s your experience with Gensim for topic modeling?"),
        (r"(.*)geopandas(.*)", "How do you work with spatial data using GeoPandas?"),
        (r"(.*)imbalanced-learn(.*)", "What techniques do you use from imbalanced-learn to address class imbalance?"),
        (r"(.*)mlflow(.*)", "How do you use MLflow for managing the machine learning lifecycle?"),
        (r"(.*)Optuna(.*)", "What’s your approach to hyperparameter tuning with Optuna?"),
        (r"(.*)Shap(.*)", "How do you use SHAP for interpreting machine learning models?"),
        (r"(.*)Eli5(.*)", "What’s your experience with ELI5 for model explainability?"),
        (r"(.*)Bayesian(.*)", "How do you use Bayesian optimization in model tuning?"),
        (r"(.*)LIME(.*)", "How do you use LIME to interpret predictions from complex models?"),
        (r"(.*)Feature engineering(.*)", "What techniques do you use for feature engineering?"),
        (r"(.*)EDA(.*)", "How do you perform exploratory data analysis for AI projects?"),
        (r"(.*)missing data(.*)", "How do you handle missing data in datasets?"),
        (r"(.*)outliers(.*)", "What’s your approach to detecting and handling outliers?"),
        (r"(.*)scaling(.*)", "When do you prefer normalization versus standardization in preprocessing?"),
        (r"(.*)categorical variables(.*)", "How do you encode categorical variables for machine learning models?"),
        (r"(.*)correlation(.*)", "What techniques do you use to analyze feature correlations?"),
        (r"(.*)imbalanced data(.*)", "How do you address imbalanced data in classification tasks?"),
        (r"(.*)sampling(.*)", "What’s your experience with oversampling and undersampling methods?"),
        (r"(.*)dimensionality(.*)", "What dimensionality reduction techniques do you use, and when?"),
        (r"(.*)clustering(.*)", "Can you describe your experience with clustering algorithms such as K-Means or DBSCAN?"),
        (r"(.*)time series(.*)", "How do you handle feature engineering for time-series data?"),
        (r"(.*)cross-validation(.*)", "What strategies do you use for cross-validation in AI projects?"),
        (r"(.*)regularization(.*)", "How do you apply regularization techniques in model training?"),
        (r"(.*)bootstrap(.*)", "What’s your understanding of bootstrapping in statistical analysis?"),
        (r"(.*)probability(.*)", "How do you use probability distributions in AI models?"),
        (r"(.*)confidence interval(.*)", "What’s your approach to calculating and interpreting confidence intervals?"),
        (r"(.*)unsupervised learning(.*)", "What unsupervised learning techniques have you applied?"),
        (r"(.*)semi-supervised learning(.*)", "Have you worked with semi-supervised learning models?"),
        (r"(.*)data visualization(.*)", "How do you use data visualization to convey insights effectively?"),
        (r"(.*)bias variance tradeoff(.*)", "Can you explain the bias-variance tradeoff and how you address it?"),
        (r"(.*)random forest(.*)", "What’s your experience with random forests for classification or regression?"),
        (r"(.*)decision trees(.*)", "How do you optimize decision trees for performance?"),
        (r"(.*)gradient boosting(.*)", "What’s your approach to tuning gradient boosting algorithms?"),
        (r"(.*)k-NN(.*)", "Can you discuss a project where you used k-Nearest Neighbors (k-NN)?"),
        (r"(.*)SVM(.*)", "What’s your experience with support vector machines for classification tasks?"),
        (r"(.*)logistic regression(.*)", "How do you use logistic regression in classification problems?"),
        (r"(.*)linear regression(.*)", "What’s your approach to applying and interpreting linear regression models?"),
        (r"(.*)data quality(.*)", "How do you ensure data quality in your AI workflows?"),
        (r"(.*)feature selection(.*)", "What methods do you use for feature selection?"),
        (r"(.*)data scaling(.*)", "Can you describe when and why you use data scaling?"),
        (r"(.*)sampling techniques(.*)", "What sampling techniques do you use for creating training datasets?"),
        (r"(.*)synthetic data(.*)", "How do you generate and validate synthetic data for machine learning?"),
        (r"(.*)versioning(.*)", "How do you manage dataset versioning in AI projects?"),
        (r"(.*)data ethics(.*)", "What’s your approach to ensuring ethical use of data in AI?"),
        (r"(.*)real-time(.*)", "How do you design AI models for real-time predictions?"),
        (r"(.*)metadata(.*)", "How do you use metadata in your data science workflows?"),
        (r"(.*)forecasting(.*)", "What techniques do you use for time series forecasting?"),
        (r"(.*)root cause analysis(.*)", "How do you approach root cause analysis in data science projects?"),
        (r"(.*)library(.*)", "What Python libraries do you use most often?"),
        (r"(.*)pandas(.*)", "Can you explain a use case where you used pandas effectively?"),
        (r"(.*)numpy(.*)", "How have you used NumPy in your projects?"),
        (r"(.*)matplotlib(.*)", "What types of visualizations have you created using Matplotlib?"),
        (r"(.*)machine learning(.*)", "Which Python libraries do you prefer for machine learning, and why?"),
        (r"(.*)tensorflow(.*)", "What’s your experience with TensorFlow?"),
        (r"(.*)project(.*)", "What Python project are you most proud of?"),
        (r"(.*)framework(.*)", "Have you worked with Python frameworks like Flask or Django?"),
        (r"(.*)flask(.*)", "How would you describe Flask compared to Django?"),
        (r"(.*)django(.*)", "What challenges have you faced while using Django?"),
        (r"(.*)automation(.*)", "Have you used Python for task automation? Can you provide examples?"),
        (r"(.*)scraping(.*)", "What’s your experience with web scraping using Python libraries like BeautifulSoup or Scrapy?"),
        (r"(.*)data(.*)", "How do you handle large datasets in Python?"),
        (r"(.*)api(.*)", "Can you describe a time when you built or consumed an API using Python?"),
        (r"(.*)debug(.*)", "What tools or techniques do you use for debugging Python code?"),
        (r"(.*)testing(.*)", "What’s your experience with Python testing frameworks like pytest?"),
        (r"(.*)asynchronous(.*)", "Have you worked with asynchronous programming in Python?"),
        (r"(.*)project(.*)", "What steps do you take to structure a Python project?"),
        (r"(.*)algorithm(.*)", "What’s the most challenging algorithm you’ve implemented in Python?"),
        (r"(.*)optimization(.*)", "How have you optimized Python code for performance?"),
        (r"(.*)oop(.*)", "What’s your approach to Object-Oriented Programming in Python?"),
        (r"(.*)functional programming(.*)", "What are your thoughts on using functional programming in Python?"),
        (r"(.*)documentation(.*)", "How do you ensure your Python code is well-documented?"),
        (r"(.*)version control(.*)", "What’s your experience with version control systems like Git for Python projects?"),
        (r"(.*)database(.*)", "What databases have you connected with Python, and how?"),
        (r"(.*)sql(.*)", "What’s your experience with executing SQL queries from Python?"),
        (r"(.*)cloud(.*)", "Have you deployed Python applications on the cloud? Which platforms did you use?"),
        (r"(.*)virtual environment(.*)", "How do you manage Python dependencies in a project?"),
        (r"(.*)package(.*)", "Have you created or published Python packages?"),
        (r"(.*)streamlit(.*)", "Have you used Streamlit for building interactive Python dashboards?"),
        (r"(.*)data visualization(.*)", "What’s your approach to data visualization using Python?"),
        (r"(.*)etl(.*)", "Have you built ETL pipelines using Python?"),
        (r"(.*)aws(.*)", "What Python tools have you used for AWS services?"),
        (r"(.*)error(.*)", "Can you describe how you handle exceptions in Python?"),
        (r"(.*)design pattern(.*)", "Which design patterns have you applied in Python projects?"),
        (r"(.*)open source(.*)", "Have you contributed to any open-source Python projects?"),
        (r"(.*)career(.*)", "How has Python shaped your career so far?"),
        (r"(.*)innovation(.*)", "Have you used Python for creating innovative solutions?"),
        (r"(.*)big data(.*)", "What’s your experience working with big data and Python?"),
        (r"(.*)ai(.*)", "Have you implemented any AI solutions using Python?"),
        (r"(.*)framework(.*)", "What Python frameworks do you find most versatile?"),
        (r"(.*)scikit-learn(.*)", "What’s your experience using scikit-learn for data analysis or machine learning?"),
        (r"(.*)optimization(.*)", "How do you ensure Python code efficiency in critical projects?"),
        (r"(.*)hobby(.*)", "What hobbies do you enjoy outside of work?"),
        (r"(.*)free time(.*)", "How do you usually spend your free time?"),
        (r"(.*)passion(.*)", "What are you most passionate about in life?"),
        (r"(.*)strength(.*)", "What do you consider to be your greatest strength?"),
        (r"(.*)weakness(.*)", "What is an area where you feel you could improve?"),
        (r"(.*)inspiration(.*)", "Who or what inspires you in your personal life?"),
        (r"(.*)goal(.*)", "What personal goal are you currently working toward?"),
        (r"(.*)travel(.*)", "Do you enjoy traveling? What’s your favorite destination?"),
        (r"(.*)dream(.*)", "What is your dream job or career aspiration?"),
        (r"(.*)value(.*)", "What values are most important to you in your personal and professional life?"),
        (r"(.*)work-life balance(.*)", "How do you maintain a healthy work-life balance?"),
        (r"(.*)stress(.*)", "How do you handle stress and stay motivated?"),
        (r"(.*)family(.*)", "How does your family influence your career decisions?"),
        (r"(.*)python(.*)", "What is your favorite Python feature and why?"),
        (r"(.*)library(.*)", "What Python libraries do you use most often?"),
        (r"(.*)pandas(.*)", "Can you explain a use case where you used pandas effectively?"),
        (r"(.*)numpy(.*)", "How have you used NumPy in your projects?"),
        (r"(.*)matplotlib(.*)", "What types of visualizations have you created using Matplotlib?"),
        (r"(.*)machine learning(.*)", "Which Python libraries do you prefer for machine learning, and why?"),
        (r"(.*)tensorflow(.*)", "What’s your experience with TensorFlow?"),
        (r"(.*)project(.*)", "What Python project are you most proud of?"),
        (r"(.*)framework(.*)", "Have you worked with Python frameworks like Flask or Django?"),
        (r"(.*)flask(.*)", "How would you describe Flask compared to Django?"),
        (r"(.*)django(.*)", "What challenges have you faced while using Django?"),
        (r"(.*)automation(.*)", "Have you used Python for task automation? Can you provide examples?"),
        (r"(.*)scraping(.*)", "What’s your experience with web scraping using Python libraries like BeautifulSoup or Scrapy?"),
        (r"(.*)data(.*)", "How do you handle large datasets in Python?"),
        (r"(.*)api(.*)", "Can you describe a time when you built or consumed an API using Python?"),
        (r"(.*)debug(.*)", "What tools or techniques do you use for debugging Python code?"),
        (r"(.*)testing(.*)", "What’s your experience with Python testing frameworks like pytest?"),
        (r"(.*)asynchronous(.*)", "Have you worked with asynchronous programming in Python?"),
        (r"(.*)project(.*)", "What steps do you take to structure a Python project?"),
        (r"(.*)algorithm(.*)", "What’s the most challenging algorithm you’ve implemented in Python?"),
        (r"(.*)optimization(.*)", "How have you optimized Python code for performance?"),
        (r"(.*)oop(.*)", "What’s your approach to Object-Oriented Programming in Python?"),
        (r"(.*)functional programming(.*)", "What are your thoughts on using functional programming in Python?"),
        (r"(.*)documentation(.*)", "How do you ensure your Python code is well-documented?"),
        (r"(.*)version control(.*)", "What’s your experience with version control systems like Git for Python projects?"),
        (r"(.*)database(.*)", "What databases have you connected with Python, and how?"),
        (r"(.*)sql(.*)", "What’s your experience with executing SQL queries from Python?"),
        (r"(.*)cloud(.*)", "Have you deployed Python applications on the cloud? Which platforms did you use?"),
        (r"(.*)virtual environment(.*)", "How do you manage Python dependencies in a project?"),
        (r"(.*)package(.*)", "Have you created or published Python packages?"),
        (r"(.*)streamlit(.*)", "Have you used Streamlit for building interactive Python dashboards?"),
        (r"(.*)data visualization(.*)", "What’s your approach to data visualization using Python?"),
        (r"(.*)etl(.*)", "Have you built ETL pipelines using Python?"),
        (r"(.*)aws(.*)", "What Python tools have you used for AWS services?"),
        (r"(.*)error(.*)", "Can you describe how you handle exceptions in Python?"),
        (r"(.*)design pattern(.*)", "Which design patterns have you applied in Python projects?"),
        (r"(.*)open source(.*)", "Have you contributed to any open-source Python projects?"),
        (r"(.*)career(.*)", "How has Python shaped your career so far?"),
        (r"(.*)innovation(.*)", "Have you used Python for creating innovative solutions?"),
        (r"(.*)big data(.*)", "What’s your experience working with big data and Python?"),
        (r"(.*)ai(.*)", "Have you implemented any AI solutions using Python?"),
        (r"(.*)framework(.*)", "What Python frameworks do you find most versatile?"),
        (r"(.*)scikit-learn(.*)", "What’s your experience using scikit-learn for data analysis or machine learning?"),
        (r"(.*)optimization(.*)", "How do you ensure Python code efficiency in critical projects?"),
    ]
    
    # Match user input to patterns
    for pattern, response in patterns:
        match = re.match(pattern, user_input, re.IGNORECASE)
        if match:
            # Check if the pattern is already in asked_questions
            if pattern not in asked_questions:
                asked_questions.add(pattern)  # Mark the pattern as asked
                return response.format(*[group.strip() for group in match.groups()])
    return get_fallback_response(fallback_responses, used_fallbacks)

if 'past' not in st.session_state:
    st.session_state['past'] = []  # User messages

if 'generated' not in st.session_state:
    st.session_state['generated'] = []  # Bot responses

def on_input_change():
    user_input = st.session_state.user_input
    st.session_state.past.append(user_input)
    bot_response = generate_response(user_input, asked_questions)
    st.session_state.generated.append(bot_response)
    st.session_state.user_input = ""

st.title("phantomMeat")

# Chat display
chat_placeholder = st.empty()

with chat_placeholder.container():
    # Always display the welcome message as the first chat message
    message("Welcome to the AI developer interview!, tell me your name please?", key="welcome_message")
    
    # Render user and bot messages
    for i in range(len(st.session_state['generated'])):
        message(st.session_state['past'][i], is_user=True, key=f"{i}_user") if i < len(st.session_state['past']) else None
        message(st.session_state['generated'][i], key=f"{i}")

# User input field
with st.container():
    st.text_input("User Input:", on_change=on_input_change, key="user_input")
